#!/usr/bin/env python3
"""Generate bounded dynamic-localisation readers for Tianxia vote tooltips.

The Zhou council already maintains ``zhx_tianzi`` and the fixed
``zhx_roster_01`` ... ``zhx_roster_80`` global event targets.  The generated
customisable localisation reads the live vote flags on whichever one of those
country scopes invokes it.  It deliberately owns no simulation state and does
not enumerate countries from a GUI refresh.
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "guangdong_independent_practice"
    / "customizable_localization"
    / "zhx_council_vote_tooltips.txt"
)
LOCALISATION_SOURCE = (
    ROOT
    / "guangdong_independent_practice"
    / "localisation_source"
    / "zhx_tianxia_debate_readable_utf8.txt"
)
LOCALISATION_BEGIN = "# ZHX_COUNCIL_VOTE_TOOLTIPS_BEGIN"
LOCALISATION_END = "# ZHX_COUNCIL_VOTE_TOOLTIPS_END"
ROSTER_SIZE = 80
CHOICES = {
    "A": "zhx_council_vote_a",
    "B": "zhx_council_vote_b",
    "C": "zhx_council_vote_c",
}


def targets() -> list[tuple[str, str]]:
    """Return ``(saved target, accessor suffix)`` in display order."""

    return [("zhx_tianzi", "Tianzi")] + [
        (f"zhx_roster_{index:02d}", f"{index:02d}")
        for index in range(1, ROSTER_SIZE + 1)
    ]


def entry_key(target: str, weight: int) -> str:
    return f"zhx_council_vote_roster_{target}_entry_{weight}"


def render_entry_accessor(
    choice: str, vote_flag: str, target: str, suffix: str
) -> str:
    """Render one Root-scoped accessor guarded before target dereference.

    Calling a custom-localisation function directly on an absent saved target
    is not documented to be safe.  All tooltip tokens therefore invoke Root,
    which is guaranteed in custom GUI country scope.  The accessor checks that
    its saved global target exists before entering that target's country scope.
    """

    lines = [
        "defined_text = {",
        f"    name = GetZhxCouncilVote{choice}Entry{suffix}",
        "    random = no",
        "",
    ]

    if choice in {"A", "B"}:
        lines.extend(
            [
                "    text = {",
                f"        localisation_key = {entry_key(target, 2)}",
                "        trigger = {",
                f"            has_saved_global_event_target = {target}",
                f"            event_target:{target} = {{",
                "                exists = yes",
                f"                has_country_flag = {vote_flag}",
                "                has_country_flag = zhx_council_vote_bonus",
                "            }",
                "        }",
                "    }",
            ]
        )

    lines.extend(
        [
            "    text = {",
            f"        localisation_key = {entry_key(target, 1)}",
            "        trigger = {",
            f"            has_saved_global_event_target = {target}",
            f"            event_target:{target} = {{",
            "                exists = yes",
            f"                has_country_flag = {vote_flag}",
            "            }",
            "        }",
            "    }",
            "    text = {",
            "        localisation_key = zhx_council_vote_roster_entry_empty",
            "        trigger = { always = yes }",
            "    }",
            "}",
        ]
    )
    return "\n".join(lines)


def render() -> str:
    header = [
        "# Generated by tools/generate_zhx_council_vote_tooltips.py.",
        "# Read-only Root-scoped presentation over zhx_tianzi and",
        "# zhx_roster_01..80.  Each accessor guards target existence before",
        "# dereferencing it; invalid, dead or non-supporting targets are empty.",
        "",
    ]
    blocks = [
        render_entry_accessor(choice, flag, target, suffix)
        for choice, flag in CHOICES.items()
        for target, suffix in targets()
    ]
    return "\n".join(header + ["\n\n".join(blocks), ""])


def roster_calls(choice: str) -> str:
    """Return the localisation token chain consumed by the readable source."""

    return "".join(
        f"[Root.GetZhxCouncilVote{choice}Entry{suffix}]"
        for _, suffix in targets()
    )


def render_localisation_block() -> str:
    common_header = (
        "§Y实时票盘§!：甲 §Y[CZH.zhx_council_vote_a_count.GetValue]§!　"
        "乙 §Y[CZH.zhx_council_vote_b_count.GetValue]§!　"
        "并立 §Y[CZH.zhx_council_vote_c_count.GetValue]§!"
        "\\n已投国数 §Y[CZH.zhx_council_voted_country_count.GetValue]§!／"
        "应投国数 §Y[CZH.zhx_council_eligible_country_count.GetValue]§!"
    )
    lines = [
        LOCALISATION_BEGIN,
        ' zhx_council_vote_roster_entry_empty:0 ""',
    ]
    for target, _ in targets():
        lines.extend(
            [
                f' {entry_key(target, 1)}:0 "§Y[{target}.GetName]§!×1　"',
                f' {entry_key(target, 2)}:0 "§Y[{target}.GetName]§!×2　"',
            ]
        )
    for choice, label in (("A", "甲案"), ("B", "乙案"), ("C", "百家并立")):
        lines.append(
            f' zhx_gui_council_vote_{choice.lower()}_roster_tt:0 "'
            f"{common_header}\\n\\n§Y支持{label}§!\\n{roster_calls(choice)}\""
        )
    lines.append(LOCALISATION_END)
    return "\n".join(lines)


def replace_generated_localisation(source: str, block: str) -> str:
    if source.count(LOCALISATION_BEGIN) != 1 or source.count(LOCALISATION_END) != 1:
        raise RuntimeError(
            "readable localisation must contain exactly one generated marker pair"
        )
    before, remainder = source.split(LOCALISATION_BEGIN, 1)
    _, after = remainder.split(LOCALISATION_END, 1)
    return before + block + after


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated file is absent or stale",
    )
    parser.add_argument(
        "--print-localisation-calls",
        action="store_true",
        help="print the A/B/C token chains used by tooltip localisation",
    )
    args = parser.parse_args()

    expected = render()
    localisation_source = LOCALISATION_SOURCE.read_text(encoding="utf-8")
    expected_localisation = replace_generated_localisation(
        localisation_source, render_localisation_block()
    )
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        stale = False
        if actual != expected:
            print(f"STALE: {OUTPUT.relative_to(ROOT)}")
            stale = True
        if localisation_source != expected_localisation:
            print(f"STALE: {LOCALISATION_SOURCE.relative_to(ROOT)}")
            stale = True
        if stale:
            return 1
        print(
            "PASS: council vote tooltip custom localisation "
            f"({ROSTER_SIZE} guarded roster slots plus Tianzi)"
        )
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"WROTE: {OUTPUT.relative_to(ROOT)}")
    LOCALISATION_SOURCE.write_text(expected_localisation, encoding="utf-8")
    print(f"WROTE: {LOCALISATION_SOURCE.relative_to(ROOT)}")

    if args.print_localisation_calls:
        for choice in CHOICES:
            print(f"{choice}: {roster_calls(choice)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
