#!/usr/bin/env python3
"""Generate the dynamic Zhou-member shield grid and presentation cache."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GUI = ROOT / "guangdong_independent_practice/interface/countrydecisionsview.gui"
CUSTOM_GUI = ROOT / "guangdong_independent_practice/common/custom_gui/zhx_tianxia_gui.txt"
EFFECTS = ROOT / "guangdong_independent_practice/common/scripted_effects/zhx_gui_roster_effects.txt"

SLOTS = 200


def replace_generated_block(path: Path, begin: str, end: str, body: str) -> None:
    text = path.read_text(encoding="utf-8")
    before, remainder = text.split(begin, maxsplit=1)
    _, after = remainder.split(end, maxsplit=1)
    path.write_text(f"{before}{begin}\n{body}\n{end}{after}", encoding="utf-8")


def gui_blocks() -> str:
    blocks = []
    for index in range(1, SLOTS + 1):
        column = (index - 1) % 24
        row = (index - 1) // 24
        x = 83 + column * 34
        y = 575 + row * 33
        blocks.append(
            "\n".join(
                [
                    "\t\t\tguiButtonType = {",
                    f"\t\t\t\tname = \"zhx_gui_member_shield_{index:02d}\"",
                    "\t\t\t\tquadTextureSprite = \"GFX_shield_small\"",
                    f"\t\t\t\tposition = {{ x = {x} y = {y} }}",
                    "\t\t\t\tclicksound = click",
                    "\t\t\t\tscripted = yes",
                    "\t\t\t}",
                ]
            )
        )
    return "\n\n".join(blocks)


def binding_blocks() -> str:
    blocks = []
    for index in range(1, SLOTS + 1):
        target = f"zhx_roster_{index:02d}"
        blocks.append(
            "\n".join(
                [
                    "custom_shield = {",
                    f"    name = zhx_gui_member_shield_{index:02d}",
                    "    potential = {",
                    "        has_global_flag = zhx_gui_roster_initialised",
                    f"        has_saved_global_event_target = {target}",
                    f"        event_target:{target} = {{",
                    "            exists = yes",
                    "            has_country_flag = zhx_member",
                    "        }",
                    "    }",
                    "    trigger = { always = yes }",
                    "    tooltip = zhx_gui_member_shield_tt",
                    f"    global_event_target = {target}",
                    "    open_country = yes",
                    "}",
                ]
            )
        )
    return "\n\n".join(blocks)


def effect_file() -> str:
    lines = [
        "# Generated by tools/generate_zhx_tianxia_roster.py.",
        "# These event targets are a GUI cache; zhx_member remains authoritative.",
        "zhx_clear_gui_roster = {",
    ]
    for index in range(1, SLOTS + 1):
        lines.extend(
            [
                "    if = {",
                f"        limit = {{ has_saved_global_event_target = zhx_roster_{index:02d} }}",
                f"        clear_global_event_target = zhx_roster_{index:02d}",
                "    }",
            ]
        )
    lines.extend(["}", "", "zhx_allocate_gui_roster_slot = {"])
    for index in range(1, SLOTS + 1):
        keyword = "if" if index == 1 else "else_if"
        lines.extend(
            [
                f"    {keyword} = {{",
                f"        limit = {{ NOT = {{ has_saved_global_event_target = zhx_roster_{index:02d} }} }}",
                f"        save_global_event_target_as = zhx_roster_{index:02d}",
                "    }",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            "zhx_build_gui_roster = {",
            "    zhx_clear_gui_roster = yes",
            "    every_country = {",
            "        limit = {",
            "            exists = yes",
            "            has_country_flag = zhx_member",
            "        }",
            "        zhx_allocate_gui_roster_slot = yes",
            "    }",
            "    set_global_flag = zhx_gui_roster_initialised",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    replace_generated_block(
        GUI,
        "\t\t\t# ZHX_ROSTER_SHIELDS_BEGIN",
        "\t\t\t# ZHX_ROSTER_SHIELDS_END",
        gui_blocks(),
    )
    replace_generated_block(
        CUSTOM_GUI,
        "# ZHX_ROSTER_BINDINGS_BEGIN",
        "# ZHX_ROSTER_BINDINGS_END",
        binding_blocks(),
    )
    EFFECTS.write_text(effect_file(), encoding="utf-8")
    print(f"generated {SLOTS} dynamic single-page roster slots")


if __name__ == "__main__":
    main()
